### ISSUE TITLE
Issue unsubscribing from a channel

### ISSUE THREAD

**Issue by chrism** [algonauti/ember-cable#39]
I connect to a channel from my Ember application like this...

```
const consumer = this.cable.createConsumer('ws://localhost:4200/websocket');
const subscription = consumer.subscriptions.create({ channel: "StationChannel", station_id: "1" }, {
  connected() {
    console.log("connected");
  },
  disconnected() {
     console.log("disconnected");
   }
});

this.subscription = subscription;
this.consumer = consumer;
```

And in Rails it logs
```
StationChannel is transmitting the subscription confirmation
StationChannel is streaming from station_1
```

But if I want to disconnect via the Ember application I can't seem to find the right way to do it.

I've tried using `unsubscribe` from `subscription.js` like this
```
this.subscription.unsubscribe();
```
And by using the `remove` directly like this
```
this.consumer.subscriptions.remove(this.subscription);
```

But I get this same error from Rails with either approach
```
Unsubscribing from channel: {"channel":"StationChannel","station_id":"1"}
Could not execute command from ({"command"=>"unsubscribe", "identifier"=>"{\"channel\":\"StationChannel\",\"station_id\":\"1\"}"}) [ArgumentError - comparison of String with 0 failed]: /opt/rubies/ruby-2.6.3/lib/ruby/2.6.0/logger.rb:457:in `<' | /opt/rubies/ruby-2.6.3/lib/ruby/2.6.0/logger.rb:457:in `add' | /my-app/app/channels/station_channel.rb:7:in `unsubscribed' | /home/vagrant/.gem/ruby/2.6.3/gems/actioncable-6.0.0.rc1/lib/action_cable/channel/base.rb:192:in `block in unsubscribe_from_channel' | /home/vagrant/.gem/ruby/2.6.3/gems/activesupport-6.0.0.rc1/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
```
Is this a bug? Any help much appreciated!

**Comment by chrism** [comment]
Ultimately this was a problem on the Rails side and unrelated to `ember-cable`.

😅
